name: Build Linux Packages Deb

on:
  push:
    branches: [ "main" ]
    paths:
      - 'linux/packages/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup version
      run: echo "DEB_VERSION=0.1-$(date '+%s')-git-${{ env.GITHUB_SHA }}" >> $GITHUB_ENV
    - name: Set version
      run: sed -i -E 's/(# *)?(Version:).*/\2 '${{ env.DEB_VERSION }}'/g' linux/packages/kali-deb.ctl
    - name: Setup dependencies
      run: sudo apt update && sudo apt install -y equivs
    - name: Build the deb
      run: equivs-build linux/packages/kali-deb.ctl
    - name: upload gh actions artifact
      uses: actions/upload-artifact@v3
      with:
        name: assaxor-dotfiles_${{ env.DEB_VERSION }}_all.deb
        path: assaxor-dotfiles_${{ env.DEB_VERSION }}_all.deb
        if-no-files-found: error
